# ─────────────────────────────────────────────────────────────────────────────
# ./netlify.toml  (place this file at the project root, *not* inside /frontend)
# ─────────────────────────────────────────────────────────────────────────────

[build]
  # We want Netlify to run these commands inside /frontend/
  base    = "frontend"
  command = "npm install && npm run build"

  # Expo’s “dist/” is where expo export:web writes everything
  # (it will create frontend/dist/index.html, assets, etc.)
  publish = "web-build"

# If you have API redirects, you can still keep this:
# [[redirects]]
#   from = "/api/*"
#   to   = "https://aetherion-mobile.onrender.com/api/:splat"
#   status = 200

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
